import { List as _List } from "../util/List.js";
import type { Dice } from "./Dice.js";

const CLASSES = [
    {
        value: "Barbarian",
        isMetalWearer: true,
        hitDice: "d12",
        isCombatant: true,
        isRanged: false
    },
    {
        value: "Bard",
        isMetalWearer: true,
        hitDice: "d8",
        isCombatant: true,
        isRanged: false
    },
    {
        race: [
            "Shifter",
            "Warforged",
            "Verdan",
            "Gith",
            "Locathah",
            "Simic Hybrid",
            "Changeling",
            "Minotaur",
            "Loxodon",
            "Vedalken",
            "Centaur",
            "Bugbear",
            "Dragonborn",
            "Draconblood",
            "Ravenite",
            "Duergar Dwarf",
            "Hill Dwarf",
            "Mountain Dwarf",
            "Drow Elf",
            "Eladrin Elf",
            "High Elf",
            "Wood Elf",
            "Sea Elf",
            "Firbolg",
            "Earth Genasi",
            "Fire Genasi",
            "Water Genasi",
            "Goliath",
            "Half-Elf",
            "Ghostwise Halfling",
            "Lightfoot Halfling",
            "Stout Halfling",
            "Halfling",
            "Half-Orc",
            "Human",
            "Kobold",
            "Lizardfolk",
            "Orc",
            "Tortle",
            "Triton",
            "Yuan-ti Pureblood",
            "Kalashtar"
        ],
        value: "Cavalier",
        isMetalWearer: true,
        hitDice: "d10",
        isCombatant: true,
        isRanged: false
    },
    {
        value: "Cleric",
        isMetalWearer: true,
        hitDice: "d8",
        isCombatant: true,
        isRanged: false
    },
    {
        value: "Druid",
        isMetalWearer: false,
        hitDice: "d8",
        isCombatant: true,
        isRanged: false
    },
    {
        value: "Fighter",
        isMetalWearer: true,
        hitDice: "d10",
        isCombatant: true,
        isRanged: false
    },
    {
        value: "Monk",
        isMetalWearer: true,
        hitDice: "d8",
        isCombatant: true,
        isRanged: false
    },
    {
        race: [
            "Shifter",
            "Warforged",
            "Verdan",
            "Gith",
            "Locathah",
            "Simic Hybrid",
            "Changeling",
            "Minotaur",
            "Loxodon",
            "Vedalken",
            "Centaur",
            "Duergar Dwarf",
            "Eladrin Elf",
            "High Elf",
            "Fire Genasi",
            "Deep Gnome",
            "Forest Gnome",
            "Rock Gnome",
            "Gnome",
            "Mark of Scribing Gnome",
            "Grung",
            "Half-Elf",
            "Stout Halfling",
            "Hobgoblin",
            "Human",
            "Tiefling",
            "Devil's Tongue Tiefling",
            "Hellfire Tiefling",
            "Winged Tiefling",
            "Yuan-ti Pureblood",
            "Kalashtar"
        ],
        value: "Mystic",
        isMetalWearer: true,
        hitDice: "d8",
        isCombatant: true,
        isRanged: false
    },
    {
        value: "Paladin",
        isMetalWearer: true,
        hitDice: "d10",
        isCombatant: true,
        isRanged: false
    },
    {
        value: "Ranger",
        isMetalWearer: true,
        hitDice: "d10",
        isCombatant: true,
        isRanged: true
    },
    {
        value: "Rogue",
        isMetalWearer: true,
        hitDice: "d8",
        isCombatant: true,
        isRanged: true
    },
    {
        value: "Sorcerer",
        isMetalWearer: true,
        hitDice: "d6",
        isCombatant: true,
        isRanged: true
    },
    {
        race: [
            "Shifter",
            "Warforged",
            "Verdan",
            "Gith",
            "Locathah",
            "Simic Hybrid",
            "Changeling",
            "Minotaur",
            "Loxodon",
            "Vedalken",
            "Centaur",
            "Aarakocra",
            "Bugbear",
            "Dragonborn",
            "Draconblood",
            "Ravenite",
            "Duergar Dwarf",
            "Drow Elf",
            "Eladrin Elf",
            "High Elf",
            "Wood Elf",
            "Sea Elf",
            "Elf",
            "Shadar-Kai",
            "Air Genasi",
            "Fire Genasi",
            "Water Genasi",
            "Deep Gnome",
            "Forest Gnome",
            "Rock Gnome",
            "Gnome",
            "Mark of Scribing Gnome",
            "Goliath",
            "Grung",
            "Half-Elf",
            "Ghostwise Halfling",
            "Lightfoot Halfling",
            "Stout Halfling",
            "Halfling",
            "Half-Orc",
            "Hobgoblin",
            "Human",
            "Kenku",
            "Kobold",
            "Lizardfolk",
            "Tabaxi",
            "Tiefling",
            "Devil's Tongue Tiefling",
            "Hellfire Tiefling",
            "Winged Tiefling",
            "Triton",
            "Yuan-ti Pureblood",
            "Kalashtar"
        ],
        value: "Trickster",
        isMetalWearer: true,
        hitDice: "d8",
        isCombatant: true,
        isRanged: false
    },
    {
        race: [
            "Shifter",
            "Warforged",
            "Verdan",
            "Gith",
            "Locathah",
            "Simic Hybrid",
            "Changeling",
            "Minotaur",
            "Loxodon",
            "Vedalken",
            "Centaur",
            "Aarakocra",
            "Bugbear",
            "Drow Elf",
            "Eladrin Elf",
            "High Elf",
            "Wood Elf",
            "Sea Elf",
            "Firbolg",
            "Air Genasi",
            "Fire Genasi",
            "Water Genasi",
            "Deep Gnome",
            "Forest Gnome",
            "Goblin",
            "Goliath",
            "Grung",
            "Half-Elf",
            "Ghostwise Halfling",
            "Lightfoot Halfling",
            "Stout Halfling",
            "Halfling",
            "Half-Orc",
            "Human",
            "Kenku",
            "Kobold",
            "Lizardfolk",
            "Tabaxi",
            "Tiefling",
            "Devil's Tongue Tiefling",
            "Hellfire Tiefling",
            "Winged Tiefling",
            "Triton",
            "Yuan-ti Pureblood",
            "Kalashtar"
        ],
        value: "Inquisitor",
        isMetalWearer: true,
        hitDice: "d8",
        isCombatant: true,
        isRanged: false
    },
    {
        race: [
            "Shifter",
            "Warforged",
            "Verdan",
            "Gith",
            "Locathah",
            "Simic Hybrid",
            "Changeling",
            "Minotaur",
            "Loxodon",
            "Vedalken",
            "Centaur",
            "Aarakocra",
            "Fallen Aasimar",
            "Protector Aasimar",
            "Scourge Aasimar",
            "Aasimar",
            "Bugbear",
            "Dragonborn",
            "Draconblood",
            "Ravenite",
            "Drow Elf",
            "Eladrin Elf",
            "High Elf",
            "Wood Elf",
            "Sea Elf",
            "Air Genasi",
            "Fire Genasi",
            "Deep Gnome",
            "Forest Gnome",
            "Goblin",
            "Goliath",
            "Grung",
            "Half-Elf",
            "Ghostwise Halfling",
            "Lightfoot Halfling",
            "Stout Halfling",
            "Halfling",
            "Half-Orc",
            "Human",
            "Kenku",
            "Kobold",
            "Tabaxi",
            "Tiefling",
            "Devil's Tongue Tiefling",
            "Hellfire Tiefling",
            "Winged Tiefling",
            "Triton",
            "Yuan-ti Pureblood",
            "Kalashtar"
        ],
        value: "Swashbuckler",
        isMetalWearer: true,
        hitDice: "d8",
        isCombatant: true,
        isRanged: false
    },
    {
        value: "Warlock",
        isMetalWearer: true,
        hitDice: "d8",
        isCombatant: true,
        isRanged: false
    },
    {
        value: "Wizard",
        isMetalWearer: true,
        hitDice: "d6",
        isCombatant: true,
        isRanged: false
    },
    {
        race: [
            "Shifter",
            "Warforged",
            "Verdan",
            "Gith",
            "Locathah",
            "Simic Hybrid",
            "Changeling",
            "Minotaur",
            "Loxodon",
            "Vedalken",
            "Centaur",
            "Aarakocra",
            "Dwarf",
            "Mark of Warding Dwarf",
            "Elf",
            "Shadar-Kai",
            "Air Genasi",
            "Fire Genasi",
            "Deep Gnome",
            "Forest Gnome",
            "Rock Gnome",
            "Gnome",
            "Mark of Scribing Gnome",
            "Goblin",
            "Grung",
            "Half-Elf",
            "Halfling",
            "Hobgoblin",
            "Human",
            "Devil's Tongue Tiefling",
            "Hellfire Tiefling",
            "Winged Tiefling",
            "Tiefling",
            "Yuan-ti Pureblood",
            "Kalashtar"
        ],
        value: "Artificer",
        isMetalWearer: true,
        hitDice: "d8",
        isCombatant: true,
        isRanged: true
    },
    {
        race: [
            "Shifter",
            "Warforged",
            "Verdan",
            "Gith",
            "Locathah",
            "Simic Hybrid",
            "Changeling",
            "Minotaur",
            "Loxodon",
            "Vedalken",
            "Centaur",
            "Aarakocra",
            "Fallen Aasimar",
            "Protector Aasimar",
            "Bugbear",
            "Wood Elf",
            "Sea Elf",
            "Fire Genasi",
            "Water Genasi",
            "Half-Elf",
            "Half-Orc",
            "Hobgoblin",
            "Human",
            "Lizardfolk",
            "Yuan-ti Pureblood"
        ],
        value: "Blood Hunter",
        isMetalWearer: true,
        hitDice: "d10",
        isCombatant: true,
        isRanged: false
    },
    {
        value: "Pacifist",
        hitDice: "d8",
        isCombatant: false,
        isMetalWearer: false,
        isRanged: false
    }
] as const;

export namespace Class {
    export const List = _List.createList<
        Class,
        {
            /**
             * Unable to use `Race` without creating a circular dependency
             */
            race?: string[];
            hitDice: Dice;
            isMetalWearer: boolean;
            isCombatant: boolean;
            isRanged: boolean;
        },
        Class
    >(CLASSES);
}

export type Class = (typeof CLASSES)[number]["value"];
